### ISSUE TITLE
打包

### ISSUE THREAD

**Issue by WoAiNianChu** [aglorice/new_xxt#1]
作者方不方便打包成可执行文件exe，如果可以的话，谢谢。

**Comment by aglorice** [comment]
可以的，等我抽个时间打包一下

**Comment by aglorice** [comment]
抱歉拖了这么久，重构了一下代码，现已经打包成了exe文件，详见[main.exe](https://github.com/aglorice/new_xxt/releases/tag/v0.2-main.exe),😅😅😅

**Comment by aglorice** [comment]
已打包
