### ISSUE TITLE
无效参数

### ISSUE THREAD

**Issue by 2446983152** [aglorice/new_xxt#10]
输入yes显示无效参数

**Comment by aglorice** [comment]
你在运行一次就可以了

**Comment by aglorice** [comment]
https://github.com/aglorice/new_xxt#%E5%A6%82%E6%9E%9C%E6%8F%90%E4%BA%A4%E7%9A%84%E6%97%B6%E5%80%99%E6%98%BE%E7%A4%BA%E6%97%A0%E6%95%88%E7%9A%84%E5%8F%82%E6%95%B0%E8%AF%B7%E9%87%8D%E6%96%B0%E8%BF%90%E8%A1%8C%E4%B8%80%E6%AC%A1%E5%B0%B1%E5%8F%AF%E4%BB%A5%E4%BA%86
