### ISSUE TITLE
EXE

### ISSUE THREAD

**Issue by Jameslai93** [aglorice/new_xxt#11]
EXE登录后拉取不到课程和题目啊

**Comment by aglorice** [comment]
有没有详细一点的提示，你重新尝试后是否也是这样

**Comment by Jameslai93** [comment]
> 没有详细一点的提示，你重新尝试后是否也是这样

登录成功,XXX
+++++++++++++++++++++++++++++++++++++++++++++++ 菜单 +++++++++++++++++++++++++++++++++++++++++++++++
1.查看课程
2.查看当前所有答案文件
3.查询所有未完成的作业
4.清除所有答案文件
5.爬取指定作业的答案
6.批量爬取指定课程的答案
7.完成作业（请先确认是否已经爬取了你想要完成作业的答案）
8.批量完成作业完成作业（请先确认是否已经爬取了你想要完成作业的答案，请填好user.json里的账号数据）
9.退出登录
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
请输入你想选择的功能：1
********************************************* 课程信息 *********************************************
┌──────┬────────┬────────┐
│ 序号 │ 课程名 │ 老师名 │
├──────┼────────┼────────┤
└──────┴────────┴────────┘
+++++++++++++++++++++++++++++++++++++++++++++++ 菜单 +++++++++++++++++++++++++++++++++++++++++++++++
1.查看课程
2.查看当前所有答案文件
3.查询所有未完成的作业
4.清除所有答案文件
5.爬取指定作业的答案
6.批量爬取指定课程的答案
7.完成作业（请先确认是否已经爬取了你想要完成作业的答案）
8.批量完成作业完成作业（请先确认是否已经爬取了你想要完成作业的答案，请填好user.json里的账号数据）
9.退出登录

你看下，这个课程是空的

**Comment by aglorice** [comment]
我暂时也看不出什么问题，你可以把这个账号给我测试一下嘛，你可以通过邮件发给我，我尝试去找到问题。

**Comment by Jameslai93** [comment]
> 我暂时也看不出什么问题，你可以把这个账号给我测试一下嘛，你可以通过邮件发给我，我试着去找到问题。

你看这个课程啊，空的啊，

**Comment by aglorice** [comment]
我使用我自己的账号测试了一下，是没有问题的。所以我不确定你的账号是什么问题。
