### ISSUE TITLE
作者有没有兴趣搞一个爬取课程章节测验和考试的

### ISSUE THREAD

**Issue by Fearless1027** [aglorice/new_xxt#15]
作者有没有兴趣搞一个爬取课程章节测验和考试的

**Comment by aglorice** [comment]
github上有现成

**Comment by Fearless1027** [comment]
> github上已经现成

请问是https://github.com/notnotype/xxt这个吗？这个有点BUG

**Comment by aglorice** [comment]
https://github.com/SocialSisterYi/CxKitty这个，这个就挺不错的

**Comment by Fearless1027** [comment]
感谢感谢！
