### ISSUE TITLE
爬取答案 可以爬取成功 答不了题

### ISSUE THREAD

**Issue by RichY0608** [aglorice/new_xxt#17]
0.46版

**Comment by aglorice** [comment]
有没有什么截图啊，或者他提示你什么

**Comment by RichY0608** [comment]
显示到检查答案那 就提交不了了

**Comment by aglorice** [comment]
你输入yes没有

**Comment by RichY0608** [comment]
![Uploading IMG_20230922_120025.jpg…]()

**Comment by aglorice** [comment]
大哥，你这图片有问题，没上传好，打不开😑
![image](https://github.com/aglorice/new_xxt/assets/93847713/ead899cc-d8fa-4bf8-9807-ec59c795ddf8)

**Comment by RichY0608** [comment]
![Uploading IMG_20230922_120025.jpg…]()

**Comment by RichY0608** [comment]
![Uploading IMG_20230922_120034.jpg…]()

**Comment by aglorice** [comment]
aglorice@qq.com,直接发我邮箱吧。还是没上传好。

**Comment by RichY0608** [comment]
> [aglorice@qq.com](mailto:aglorice@qq.com),直接发我邮箱吧。还是没上传好。

发给你了 看一下

**Comment by aglorice** [comment]
其他的作业有问题不，看了下，原因应该是答案的id和题的id对不上，虽然题是一样的，答案的来源是否是同一个班的？如果可以，你把账号和答案文件用邮箱发我，我再看看

**Comment by aglorice** [comment]
![IMG_20230922_145214_edit_197852008046484](https://github.com/aglorice/new_xxt/assets/93847713/a8eb4ae0-c4b2-4b90-bb92-ef44df171ad8)解决了，等会再提交。
