### ISSUE TITLE
隔壁班级一样的题目也不行

### ISSUE THREAD

**Issue by RichY0608** [aglorice/new_xxt#18]

**Comment by aglorice** [comment]
确实是这样，需要他们本班的人爬取的答案，因为我是靠id匹配的，而不是题目内容。

**Comment by RichY0608** [comment]
能不能写一个爬取测试题的




别等不该等的人
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aglorice/new_xxt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月23日(星期六) 上午8:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aglorice/new_xxt] 隔壁班级一样的题目也不行 (Issue #18)





 
Closed #18 as completed.

**Comment by aglorice** [comment]
目前不会有啥新功能更新了。
