### ISSUE TITLE
答案的判断方法

### ISSUE THREAD

**Issue by WoAiNianChu** [aglorice/new_xxt#2]
今天在手机上的Termux成功运行，发现一个小问题。
**问题：对于多选题的正确判断方法不严谨。多选题有三种最终结果，一种是完全正确，还有半对半错，最后一种完全错误。**
已完成人的答案是半对半错，结果程序把半对半错的的选项同步到未完成人的作业上，理论上应该是完全正确的答案填写上。

**Comment by aglorice** [comment]
这里这样做是是个无赖的办法，因为很多题不会放出正确答案，我们也无法判断提供答案的账号的答案那个是正确的，所以这里只能做出这样的处理

**Comment by WoAiNianChu** [comment]
> 因为很多题不会放出正确答案，我们也无法判断提供答案的账号的答

的确有的情况下答完题后不会显示正确答案，只会告诉你对错。但是多选题即使显示正确答案，半对半错的答案还是会照搬的。

**Comment by aglorice** [comment]
目前只支持有正确答案的情况，对于只有自己的答案的情况，可能会在后续添加该功能。
