### ISSUE TITLE
exe5.0版本多用户批量完成作业会闪退

### ISSUE THREAD

**Issue by JBright1030** [aglorice/new_xxt#20]
exe5.0版本多用户批量完成作业会闪退，做单个用户的没问题，度用户会闪退，难道是因为打包造成的吗？源码的我还没试过。

**Comment by aglorice** [comment]
是否能提供几个测试测试账号。

**Comment by aglorice** [comment]
> exe5.0版本多用户批量完成作业会闪退，做单个用户的没问题，度用户会闪退，难道是因为打包造成的吗？源码的我还没试过。

可以通过邮箱发我

**Comment by JBright1030** [comment]
15687419007hsm123456717261152806z343918076315708817204ydl1379801930885357033441314520h这些都做过了，但是可以重做，你点重做你测试一下，课程都是形式政策，500道题作业。辛苦你了大佬发自我的 iPhone在 2023年11月21日，16:11，友人A ***@***.***> 写道：﻿

exe5.0版本多用户批量完成作业会闪退，做单个用户的没问题，度用户会闪退，难道是因为打包造成的吗？源码的我还没试过。

可以通过邮箱发我

**Comment by aglorice** [comment]
> exe5.0版本多用户批量完成作业会闪退，做单个用户的没问题，度用户会闪退，难道是因为打包造成的吗？源码的我还没试过。

解决了
