### ISSUE TITLE
大佬你好,请问这个SyntaxError: invalid syntax是什么原因

### ISSUE THREAD

**Issue by nihaodaming** [aglorice/new_xxt#21]
![$WF$5${E@WUMVV7DRBKW 1H](https://github.com/aglorice/new_xxt/assets/122172408/d6c938e8-619f-4e31-9866-fc3fbf9171b7)
我从代码里看不出有问题

**Comment by aglorice** [comment]
> ![$WF$5${E@WUMVV7DRBKW 1H](https://github.com/aglorice/new_xxt/assets/122172408/d6c938e8-619f-4e31-9866-fc3fbf9171b7)
> 我从代码里看不出有问题
> 

你的python 版本是不是太低了，你升级到3.10以上看看。

**Comment by nihaodaming** [comment]
感谢大佬,成功打开了
