### ISSUE TITLE
失效解析

### ISSUE THREAD

**Issue by whis222** [aglorice/new_xxt#24]
作业是否可以重做解析标签失效，可以修复下吗

**Comment by aglorice** [comment]
能提供一个测试账号吗并将课程和相对应的作业发到我的邮箱aglorice2@gmail.com

**Comment by aglorice** [comment]
> 作业是否可以重做解析标签失效，可以修复下吗

新的版本有日志功能，你可以把日志发我看下

**Comment by whis222** [comment]
嗯反馈了

**Comment by aglorice** [comment]
> 嗯反馈了

可以发下账号密码吗通过邮箱，还有对应的答案文件，不然我不好复现

**Comment by aglorice** [comment]
@whis222
<img width="788" alt="{100F6116-BEFD-4a5c-919B-AB51C098BC68}" src="https://github.com/aglorice/new_xxt/assets/93847713/ca15bb09-7472-4c9b-a383-2c099bcaab10">
我尝试自己创建了一个作业并实验了重做功能，发现并没有任何问题。我不确定你那里是什么问题。
