### ISSUE TITLE
无法正常运行

### ISSUE THREAD

**Issue by WoAiNianChu** [aglorice/new_xxt#3]
![图片](https://user-images.githubusercontent.com/112552691/232735748-ef3c0943-6f09-45b0-8fcc-45e6c199b85f.png)

**Comment by aglorice** [comment]
你可以试着检查一下answer.json的格式

**Comment by WoAiNianChu** [comment]
> 你可以试着检查一下answer.json的格式

前几天第一次可以正常使用，今天就不可以了，换了两部手机都是同样的问题。只动了账号密码和课程，那个文件没动。

**Comment by aglorice** [comment]
能否打开answer.json的文件让我看看

**Comment by WoAiNianChu** [comment]
> 能否打开answer.json的文件让我看看

![Screenshot_20230418-183923_MT管理器](https://user-images.githubusercontent.com/112552691/232755930-10450700-4415-4928-8b76-833129e466e3.png)

**Comment by aglorice** [comment]
似乎应该是爬取答案的时候出现了问题

**Comment by aglorice** [comment]
⊙ω⊙
