### ISSUE TITLE
密码错误

### ISSUE THREAD

**Issue by WoAiNianChu** [aglorice/new_xxt#4]
同样的账号密码，旧版没有这个问题
![图片](https://user-images.githubusercontent.com/112552691/233408961-e4711f23-61f7-4192-9d5d-0a711e97f72e.png)

**Comment by WoAiNianChu** [comment]
> 你是否正确的配置了user.json

不好意思，没有仔细看新版文档，冲动了。现在已经成功使用了，以前的那个问题也解决了。**还有批量很好用**

**Comment by lijinge001** [comment]
请问你是怎么弄好的啊，我也是这个问题

**Comment by aglorice** [comment]
> 
已经重构了代码，不会再出现之前的问题。
