### ISSUE TITLE
老哥 ！请求帮助

### ISSUE THREAD

**Issue by 2682856025** [aglorice/new_xxt#8]
<img width="340" alt="截屏2023-05-27 下午6 20 50" src="https://github.com/aglorice/new_xxt/assets/106012957/80461768-e552-4754-abb2-22849cde95e1">
老哥 不知道你搞没搞过考试 这个题目提交参数是啥 没搞出来

**Comment by aglorice** [comment]
这个我还没有弄过，不过从你这里也大概看的出一些东西。

1. _edt 这应该就是一个16位时间戳，你可以这样得到它`int(time.time() * 1000000)`
2. version 这应该是一个固定的值，你应该可以在页面的`<input>`中找到它的值。
3. qid 这也应该是存在在页面中的`<input>`的值。
4. rd 这个值可能是动态的，你可能需要去扣它的js代码。
5. value 不确定
6. pos 这个也可能需要扣js代码

**Comment by 2682856025** [comment]
rd和pos我是一直没扣出来 老哥能帮忙扣一下吗

**Comment by aglorice** [comment]
抱歉，最近没啥时间😅😅😅。

**Comment by 2682856025** [comment]
value也失败了 这三个
